export const startingFrames = [
  {
    roll1: null,
    roll2: null,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
  },
  {
    roll1: null,
    roll2: null,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
  },
  {
    roll1: null,
    roll2: null,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
  },
  {
    roll1: null,
    roll2: null,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
  },
  {
    roll1: null,
    roll2: null,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
  },
  {
    roll1: null,
    roll2: null,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
  },
  {
    roll1: null,
    roll2: null,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
  },
  {
    roll1: null,
    roll2: null,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
  },
  {
    roll1: null,
    roll2: null,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
  },
  {
    roll1: null,
    roll2: null,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
  },
];
